from __future__ import annotations

from .types import SleeveManifest, TimeframeBundle


BUNDLE_MANIFESTS: dict[str, TimeframeBundle] = {
    "bundle_intraday_core": TimeframeBundle(
        name="bundle_intraday_core",
        fast_tf="15m",
        base_tf="1h",
        slow_tf="4h",
        label_horizon_hours=8.0,
        max_hold_hours=24.0,
        feature_window_hours={"fast": 6.0, "base": 24.0, "slow": 72.0},
    ),
    "bundle_swing_core": TimeframeBundle(
        name="bundle_swing_core",
        fast_tf="1h",
        base_tf="4h",
        slow_tf="1d",
        label_horizon_hours=24.0,
        max_hold_hours=96.0,
        feature_window_hours={"fast": 24.0, "base": 72.0, "slow": 240.0},
    ),
}


# The requested source list contains 15 experimental sleeves even though the plan
# summary said 14. We keep all listed sleeves and add one foundation sleeve so V2
# starts from known edge instead of experimentation alone.
SLEEVE_MANIFESTS: dict[str, SleeveManifest] = {
    "trend_1h_directional": SleeveManifest(
        name="trend_1h_directional",
        family="foundation",
        side_mode="long",
        model_family="legacy_strategy",
        feature_profile="price_context",
        label_horizon_hours=3.0,
        max_hold_hours=3.0,
        min_confidence=0.58,
        stop_atr_mult=7.0,
        edge_scale_bps=250.0,
        cluster="foundation",
        activation_rule="Port of exp494 1h directional entry logic using aligned 15m/1h/4h strategy predictions.",
        portfolio_weight=1.0,
    ),
    "bear_1h_calibrated": SleeveManifest(
        name="bear_1h_calibrated",
        family="foundation",
        side_mode="short",
        model_family="legacy_strategy",
        feature_profile="price_context",
        label_horizon_hours=2.0,
        max_hold_hours=2.0,
        min_confidence=0.56,
        stop_atr_mult=7.0,
        edge_scale_bps=220.0,
        cluster="foundation_short",
        activation_rule="Port of exp494 calibrated bear short lane using aligned 15m/1h/4h strategy predictions.",
        portfolio_weight=1.0,
    ),
    "bear_1h_foundation": SleeveManifest(
        name="bear_1h_foundation",
        family="foundation",
        side_mode="short",
        model_family="legacy_strategy",
        feature_profile="price_context",
        label_horizon_hours=3.0,
        max_hold_hours=3.0,
        min_confidence=0.54,
        stop_atr_mult=7.0,
        edge_scale_bps=240.0,
        cluster="foundation_short",
        activation_rule="Port of exp494 broad short foundation lane combining bear_fortress priority with calibrated bear fallback.",
        portfolio_weight=1.0,
    ),
    "trend_breakout": SleeveManifest(
        name="trend_breakout",
        family="trend",
        side_mode="long",
        label_horizon_hours=12.0,
        max_hold_hours=24.0,
        target_sigma=0.85,
        min_confidence=0.60,
        cluster="trend",
        activation_rule="Breakout with positive structure, expanding volume, and slow-trend support.",
    ),
    "trend_pullback": SleeveManifest(
        name="trend_pullback",
        family="trend",
        side_mode="long",
        label_horizon_hours=18.0,
        max_hold_hours=36.0,
        target_sigma=0.75,
        min_confidence=0.58,
        cluster="trend",
        activation_rule="Pullback into support inside an established uptrend.",
    ),
    "trend_continuation": SleeveManifest(
        name="trend_continuation",
        family="trend",
        side_mode="long",
        label_horizon_hours=12.0,
        max_hold_hours=30.0,
        target_sigma=0.75,
        min_confidence=0.58,
        cluster="trend",
        activation_rule="Fast/base momentum continuation with aligned slow trend.",
    ),
    "sideways_mean_reversion": SleeveManifest(
        name="sideways_mean_reversion",
        family="mean_reversion",
        side_mode="long",
        label_horizon_hours=8.0,
        max_hold_hours=20.0,
        target_sigma=0.65,
        min_confidence=0.58,
        cluster="mean_reversion",
        activation_rule="Oversold reversion inside sideways regime.",
        portfolio_weight=1.0,
        reentry_cooldown_hours=0.0,
        reentry_cooldown_scope="sleeve",
    ),
    "post_extension_snapback": SleeveManifest(
        name="post_extension_snapback",
        family="mean_reversion",
        side_mode="both",
        label_horizon_hours=8.0,
        max_hold_hours=18.0,
        target_sigma=0.65,
        min_confidence=0.58,
        cluster="mean_reversion",
        activation_rule="Snapback after local price extension away from VWAP.",
        portfolio_weight=1.0,
        reentry_cooldown_hours=0.0,
        reentry_cooldown_scope="sleeve",
    ),
    "volatility_reversion": SleeveManifest(
        name="volatility_reversion",
        family="mean_reversion",
        side_mode="both",
        label_horizon_hours=12.0,
        max_hold_hours=24.0,
        target_sigma=0.60,
        min_confidence=0.57,
        cluster="mean_reversion",
        activation_rule="Mean reversion after volatility expansion in non-trend tape.",
    ),
    "funding_carry": SleeveManifest(
        name="funding_carry",
        family="carry",
        side_mode="both",
        label_horizon_hours=12.0,
        max_hold_hours=36.0,
        target_sigma=0.55,
        min_confidence=0.56,
        cluster="carry",
        activation_rule="Carry capture from extreme positive/negative funding.",
    ),
    "basis_dislocation": SleeveManifest(
        name="basis_dislocation",
        family="carry",
        side_mode="both",
        label_horizon_hours=8.0,
        max_hold_hours=24.0,
        target_sigma=0.60,
        min_confidence=0.56,
        cluster="carry",
        activation_rule="Fade abrupt basis/funding shocks that overshoot local trend.",
    ),
    "cross_asset_relative_strength": SleeveManifest(
        name="cross_asset_relative_strength",
        family="relative_strength",
        side_mode="long",
        label_horizon_hours=18.0,
        max_hold_hours=36.0,
        target_sigma=0.70,
        min_confidence=0.58,
        cluster="relative_strength",
        activation_rule="Long strongest cross-sectional leaders with slow trend support.",
        portfolio_weight=1.0,
    ),
    "leader_laggard_rotation": SleeveManifest(
        name="leader_laggard_rotation",
        family="relative_strength",
        side_mode="long",
        label_horizon_hours=12.0,
        max_hold_hours=30.0,
        target_sigma=0.65,
        min_confidence=0.58,
        cluster="relative_strength",
        activation_rule="Rotation into emerging leaders before full trend confirmation.",
    ),
    "macro_beta_dispersion": SleeveManifest(
        name="macro_beta_dispersion",
        family="relative_strength",
        side_mode="both",
        label_horizon_hours=12.0,
        max_hold_hours=30.0,
        target_sigma=0.65,
        min_confidence=0.58,
        cluster="relative_strength",
        activation_rule="Dispersion trade conditioned on cross-asset stress and macro beta spread.",
    ),
    "macro_event_drift": SleeveManifest(
        name="macro_event_drift",
        family="event",
        side_mode="both",
        label_horizon_hours=12.0,
        max_hold_hours=24.0,
        target_sigma=0.60,
        min_confidence=0.57,
        cluster="event",
        activation_rule="Drift continuation after macro and major-market event impulses.",
    ),
    "post_event_mean_reversion": SleeveManifest(
        name="post_event_mean_reversion",
        family="event",
        side_mode="both",
        label_horizon_hours=8.0,
        max_hold_hours=20.0,
        target_sigma=0.60,
        min_confidence=0.57,
        cluster="event",
        activation_rule="Fade post-event overreaction after sentiment shock extremes.",
    ),
    "bear_stress_short": SleeveManifest(
        name="bear_stress_short",
        family="short",
        side_mode="short",
        label_horizon_hours=12.0,
        max_hold_hours=30.0,
        target_sigma=0.75,
        min_confidence=0.60,
        cluster="short",
        activation_rule="Short breakdowns during bear-regime stress with aligned slow trend.",
    ),
    "squeeze_failure_short": SleeveManifest(
        name="squeeze_failure_short",
        family="short",
        side_mode="short",
        label_horizon_hours=8.0,
        max_hold_hours=20.0,
        target_sigma=0.70,
        min_confidence=0.59,
        cluster="short",
        activation_rule="Short failed squeezes after overbought exhaustion and bearish reversal structure.",
    ),
}
